version: "3.8"

services:
  app:
    image: platziapp
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: npx nodemon index.js

  db:
    image: mongo
